github:
  description: "Apache Sling Content Package Archetype"
  labels:
  - "java"
  - "sling"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
notifications:
  jira_options: "link"
